api/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register(r'posts', views.PostViewSet)

# Wire up your API using automatic URL routing.
# Additionally, you include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

blog/urls.py
from django.urls import path
from blog import views


app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('<int:pk>', views.PostDetailView.as_view(), name='detail'),
]

django_blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('api/', include('api.urls')),
    path('', RedirectView.as_view(url='blog/')),
]

api/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=140)
    text = models.TextField()
    published = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-published']

api/views.py
from blog.models import Post
from rest_framework import viewsets
from rest_framework import permissions
from .serializers import PostSerializer


class PostViewSet(viewsets.ModelViewSet):
    """API endpoint that allows posts to be viewed or edited."""
    queryset = Post.objects.all().order_by('-published')
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticated]

blog/views.py
from django.shortcuts import render
from .models import Post
from django.views import generic


# Create your views here.
# def index(request):
#     posts = Post.objects.all()
#     context = {'posts': posts}
#     return render(request, 'blog/index.html', context)

class PostListView(generic.ListView):
    model = Post
    paginate_by = 6
    template_name = 'blog/index.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'blog/detail.html'

# def detail(request, pk):
#     post = Post.objects.get(pk=pk)
#     context = {'post': post}
#     return render(request, 'blog/detail.html', context)

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Hello, world!</title>
    <style>
      body {
        position: static;
        font-family: Georgia, serif;
      }
      body::before {
        content: "";
        background-image: url("{% static 'blog/images/background.png' %}");
        background-size: cover;
        background-repeat: no-repeat;
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: -1;
        opacity: .16;
      }
    </style>
  </head>
  <body>

  <div class="px-4 py-5 text-center">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="display-4">Sample Blog App</h1>
        <p class="lead fw-normal fs-4">By: Blog Author</p>
      </div>
    </div>
  </div>
{% block content %}

{% endblock content %}

  <div class="container">
    {% block pagination %}
      {% if is_paginated %}
        <div class="pagination m-3">
          <span class="page-links">
            {% if page_obj.has_previous %}
              <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}" class="btn btn-primary btn-sm">previous</a>
            {% endif %}
            <span class="page-current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}" class="btn btn-primary btn-sm">next</a>
            {% endif %}
          </span>
        </div>
      {% endif %}
    {% endblock %}
  </div>
</body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}


</div>
    <div class="container">
        <h1><strong>{{ post.title }}</strong></h1>
        <br>
        
        
        <p class="lead"> {{ post.text }}</p>
        <p><em><small> -{{ post.published }} </small></em></p>
    </div>

{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

    {% block content %}

    <!-- HTML elements with Bootstrap classes -->
    
    <div class="container">
      <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for post in post_list %}
        <div class="col">
          <div class="card m-3" style="background-color: #FFFDF2;">
            <div class="card-body">
              <h1 class="card-title">{{ post.title }}</h1>
              <p class="card-text text-muted small">{{ post.published }}</p>
              <p class="card-text">{{ post.text|capfirst|truncatechars:30 }}.</p>
              <a href="{% url 'blog:detail' post.id %}" class="btn btn-primary">Read More</a>
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
    </div>

    {% endblock content %}